// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQPEICh8CZ0UbCW9ent6stT-8hMy4aZE',
    appId: '1:597360007405:web:b079f7464a54eae47554e4',
    messagingSenderId: '597360007405',
    projectId: 'flare-chat-26bea',
    authDomain: 'flare-chat-26bea.firebaseapp.com',
    storageBucket: 'flare-chat-26bea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7NRFa65PvdPKl71MzhNO-MBZzaOw0js',
    appId: '1:597360007405:android:dd380a70f40b79907554e4',
    messagingSenderId: '597360007405',
    projectId: 'flare-chat-26bea',
    storageBucket: 'flare-chat-26bea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBbUuNFPKjBGpURKWoQ-o2gM_p3OmPUls',
    appId: '1:597360007405:ios:1cbfd03183505ab67554e4',
    messagingSenderId: '597360007405',
    projectId: 'flare-chat-26bea',
    storageBucket: 'flare-chat-26bea.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
